<?php

/**
 * Implements hook_node_info().
 */
function friend_node_info() {
  return [
    'friend' => [
      'name' => t('Friend'),
      'base' => 'friend',
      'description' => t('Friend content type.'),
      'title_label' => t('Name'),
      'locked' => TRUE,
    ],
  ];
}

/**
 * Implements hook_node_type_insert().
 */
function friend_node_type_insert($content_type) {
  if ($content_type->type == 'friend') {
    foreach (_friend_installed_fields() as $field) {
      field_create_field($field);
    }

    // Create all the instances for our fields.
    foreach (_friend_installed_instances() as $instance) {
      $instance['entity_type'] = 'node';
      $instance['bundle']      = 'friend';

      field_create_instance($instance);
    }
  }
}

/**
 * Implements hook_cron().
 */
function friend_cron() {
  $last_run = variable_get('friend_last_cron', 0);

  if (date('Ymd') != date('Ymd', $last_run)) {
    // New day, lets check birthdays to send emails
    require_once 'src/BirthdayMailer.php';

    $birthdayMailer = new BirthdayMailer();
    $birthdayMailer->checkDates();

    variable_set('friend_last_cron', time());
  }
}

function friend_mail($key, &$message, $params) {
  switch ($key) {
    case 'birthday':
      require_once 'src/BirthdayMailer.php';
      $message['subject'] = BirthdayMailer::getEmailSubject();
      $message['body']    = BirthdayMailer::getEmailBody($params);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function friend_theme($existing, $type, $theme, $path) {
  $theme = [];

  $theme['node__friend'] = [
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--friend',
    'path' => drupal_get_path('module', 'friend') . '/templates',
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_page().
 */
function friend_preprocess_page(&$vars) {
  if (!empty($vars['node'])) {
    $node = $vars['node'];
    if ($node->type == 'friend') {
      $vars['title'] = 'Friend data';
    }
  }
}

function _friend_installed_fields() {
  return [
		'friend_first_name'	=> [
			'field_name'  => 'friend_first_name',
			'type'        => 'text',
			'cardinality' => 1,
      'settings'    => [
        'max_length' => 60,
			],
    ],
		'friend_email'	=> [
			'field_name'  => 'friend_email',
			'type'        => 'text',
			'cardinality' => 1,
      'settings'    => [
        'max_length' => 60,
			],
    ],
    'friend_birthday' => [
      'field_name'  => 'friend_birthday',
      'type'        => 'date',
      'cardinality' => 1,
      'settings'    => [
        'granularity' => drupal_map_assoc(['year', 'month', 'day']),
        'tz_handling' => 'none',
			],
		],
    'friend_avatar' => [
      'field_name'  => 'friend_avatar',
      'type'        => 'image',
      'cardinality' => 1,
		],
  ];
}

function _friend_installed_instances() {
  return [
		'friend_first_name'	=> [
			'field_name' => 'friend_first_name',
			'label' => t('First name'),
			'required' => TRUE,
			'widget' => [
				'type' => 'text_textfield'
      ],
    ],
		'friend_email' => [
			'field_name' => 'friend_email',
			'label' => t('Email address'),
			'required' => TRUE,
			'widget' => [
				'type' => 'text_textfield'
      ],
    ],
		'friend_birthday' => [
			'field_name' => 'friend_birthday',
			'label' => t('Birthday'),
			'required' => TRUE,
			'widget' => [
				'type' => 'date_popup',
      ],
    ],
    'friend_avatar' => [
      'field_name'  => 'friend_avatar',
      'label'       => t('Avatar'),
      'required'    => FALSE,
      'widget' => [
        'type'    => 'image_image',
        'weight'  => 2.10,
      ],
      'display' => [
        'friend_list' => [
          'label' => 'hidden',
          'type' => 'image_link_content__thumbnail',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_form().
 */
function friend_form($node, $form_state) {
  return node_content_form($node, $form_state);
}
